### ISSUE TITLE
sfxt.hpp:34:12: error：expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by simintao** [OpenTimer/OpenTimer#37]
**Describe the bug**
build error on cygwin platform

**To Reproduce**
build on cygwin, gcc version is 9.3

**Expected behavior**
build success

**Screenshots**
![image](https://user-images.githubusercontent.com/54231100/91383662-44153880-e85f-11ea-9114-04a04b7b3571.png)

**Desktop (please complete the following information):**
 - OS: win 10 cygwin
 - Version gcc-9.3

**Comment by K0rrid0r** [comment]
I have the same error, have this been resolved @simintao ?

![image](https://user-images.githubusercontent.com/56724286/113369420-9a9ca500-9361-11eb-9daa-dce07922540c.png)


Desktop:

OS: win 8.1 cygwin
Version gcc-10.2.0
